Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Estimate the solar position with a specific SPA defined with the argument 'method' 
solpos_nrel = pvlib.solarposition.get_solarposition(times, site.latitude, site.longitude, site.altitude, method='nrel_numpy')
solpos_pyephem = pvlib.solarposition.get_solarposition(times, site.latitude, site.longitude, site.altitude, method='pyephem')
solpos_ephemeris = pvlib.solarposition.get_solarposition(times, site.latitude, site.longitude, site.altitude, method='ephemeris')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pvlib/solarposition.py[0m in [0;36mpyephem[0;34m(time, latitude, longitude, altitude, pressure, temperature, horizon)[0m
[1;32m    633[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 634[0;31m         [0;32mimport[0m [0mephem[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    635[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'ephem'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_1939/800067987.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Estimate the solar position with a specific SPA defined with the argument 'method'[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0msolpos_nrel[0m [0;34m=[0m [0mpvlib[0m[0;34m.[0m[0msolarposition[0m[0;34m.[0m[0mget_solarposition[0m[0;34m([0m[0mtimes[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlatitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlongitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0maltitude[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0;34m'nrel_numpy'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0msolpos_pyephem[0m [0;34m=[0m [0mpvlib[0m[0;34m.[0m[0msolarposition[0m[0;34m.[0m[0mget_solarposition[0m[0;34m([0m[0mtimes[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlatitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlongitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0maltitude[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0;34m'pyephem'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0msolpos_ephemeris[0m [0;34m=[0m [0mpvlib[0m[0;34m.[0m[0msolarposition[0m[0;34m.[0m[0mget_solarposition[0m[0;34m([0m[0mtimes[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlatitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0mlongitude[0m[0;34m,[0m [0msite[0m[0;34m.[0m[0maltitude[0m[0;34m,[0m [0mmethod[0m[0;34m=[0m[0;34m'ephemeris'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pvlib/solarposition.py[0m in [0;36mget_solarposition[0;34m(time, latitude, longitude, altitude, pressure, method, temperature, **kwargs)[0m
[1;32m    119[0m                            [0maltitude[0m[0;34m=[0m[0maltitude[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    120[0m                            [0mpressure[0m[0;34m=[0m[0mpressure[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 121[0;31m                            temperature=temperature, **kwargs)
[0m[1;32m    122[0m     [0;32melif[0m [0mmethod[0m [0;34m==[0m [0;34m'ephemeris'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    123[0m         ephem_df = ephemeris(time, latitude, longitude, pressure, temperature,

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pvlib/solarposition.py[0m in [0;36mpyephem[0;34m(time, latitude, longitude, altitude, pressure, temperature, horizon)[0m
[1;32m    634[0m         [0;32mimport[0m [0mephem[0m[0;34m[0m[0;34m[0m[0m
[1;32m    635[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 636[0;31m         [0;32mraise[0m [0mImportError[0m[0;34m([0m[0;34m'PyEphem must be installed'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    637[0m [0;34m[0m[0m
[1;32m    638[0m     [0;31m# if localized, convert to UTC. otherwise, assume UTC.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: PyEphem must be installed
ImportError: PyEphem must be installed

